# è¿™æ˜¯è‡ªå®šä¹‰çš„ä¸»é¢˜é…ç½®ï¼Œéé»˜è®¤ä¸»é¢˜é…ç½®

########################################################################

# ç½‘é¡µå¤–è§‚é…ç½®
# mode: light | dark | auto
mode: auto

# ç½‘ç«™
title: å¶å­çš„èŠ±å›­
subtitle: 'é¡ä¸æœ‰åˆï¼Œé²œå…‹æœ‰ç»ˆ'
description: '@Misaka-Clover'
keywords: 'ä¸ªäººåšå®¢,å­¦ä¹ ,æŠ€æœ¯,OpenMV,SCUT,Hexo,yun'
author: å¶å­
language: zh-CN
timezone: 'Asia/Shanghai'

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
# å¥½åƒæ²¡èµ·ä½œç”¨â€¦â€¦
# 2024-06-26 è¿˜æ˜¯æ²¡èµ·ä½œç”¨â€¦â€¦
per_page: 30
pagination_dir: page

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://mskclover.com/
permalink: :year/:month/:day/:title/
permalink_defaults: 
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yun

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/misaka-clover/misaka-clover.github.io #æ­¤å‰æ–°å»ºä»“åº“çš„é“¾æ¥
  branch: master #é»˜è®¤ä½¿ç”¨masteråˆ†æ”¯
  message: Update Hexo Static Content #ä½ å¯ä»¥è‡ªå®šä¹‰æ­¤æ¬¡éƒ¨ç½²æ›´æ–°çš„è¯´æ˜

# é¦–é¡µçš„æ ‡è¯­åŠ¨ç”»
banner:
  enable: true
  title: å¶å­çš„èŠ±å›­
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

# é¦–é¡µçš„å…¬å‘Š
notice:
  enable: false
  content: æ¬¢è¿æ¥åˆ°æˆ‘çš„èŠ±å›­ï¼Œè¯·éšæ„å‚è§‚ï¼

# ç½‘é¡µçš„èƒŒæ™¯å›¾ç‰‡
bg_image:
  enable: true
  url: /images/background.jpg
  dark: /images/galaxy.jpg
  blur: 3px
  opacity: 0.8

# éšæœºå¤šè¾¹å½¢èƒŒæ™¯
trianglify:
  enable: false
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

# çƒŸèŠ±æ•ˆæœ
fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

# Medium Zoom æ”¾å¤§é¢„è§ˆå›¾ç‰‡
# ç‚¹å‡»æ–‡ç« å›¾ç‰‡ï¼Œæ”¾å¤§é¢„è§ˆã€‚
medium_zoom: true

# æ»šåŠ¨æµ®ç°æ•ˆæœ
# https://github.com/jlmakes/scrollreveal
scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

# å…‰æ ‡
cursor:
  enable: true
  # default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  # pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  # text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur



########################################################################

# ä¾§æ 
# æ ‡ç­¾
sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20
  
  # ä¾§æ é»˜è®¤å±•å¼€ï¼šæµ‹è¯•
  # display: always

# å¤´åƒå›¾ç‰‡é…ç½®
avatar:
  enable: true
  url: /images/avatar/avatar.jpg 
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ¥¬
    message: ä»Šå¤©ä¹Ÿæ˜¯ç¾å¥½çš„ä¸€å¤©å‘¢

# è®¾ç½®å¯¼èˆªæ 
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
  custom:
    title: ç•™è¨€æ¿
    path: about/#comment
    icon: ri:clipboard-line

# å‹é“¾
pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
#  - name: å–œæ¬¢çš„å¥³å­©å­
#    url: /girls/
#    icon: ri:women-line
#    color: hotpink

# # å¥³å‹
# girls:
#   enable: false


# ä¾§æ ç¤¾äº¤å›¾æ ‡
social:
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    # å›¾æ ‡é€‰å–å‚è§ï¼šhttps://yun.yunyoujun.cn/about/icon.html
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: GitHub
    link: https://github.com/misaka-clover
    icon: ri:github-line
    color: "#181717"
  - name: Twitter
    link: https://twitter.com/Misaka_Clover
    icon: ri:twitter-line
    color: '#1da1f2'
  - name: Mastodon
    link: https://g0v.social/@Misaka_Clover
    icon: ri:mastodon-line
    color: purple
  - name: E-Mail
    link: mailto:cover@mskclover.com
    icon: ri:mail-line
    color: "#8E71C1"
  - name: Travelling
    link: https://www.travellings.cn/go.html
    icon: ri:train-line
    color: black

# RSS é…ç½®
# è¿˜éœ€è¦ä¸Šç½‘æŸ¥ä¸€ä¸‹â€¦â€¦
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 10
  hub:
  content: true
  content_limit:
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template: /feed/atom.xml

########################################################################

# æ–‡ç« 
# å†…å®¹å¡ç‰‡
post_card:
  opacity: 0.8

# æ–‡ç« ä¿¡æ¯
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

# ç›®å½•
toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  collapse: false

# ç¼–è¾‘é“¾æ¥
post_edit:
  enable: false
  url: https://github.com/misaka-clover/misaka-clover.github.io/tree/hexo/source/

# ç‰ˆæƒ
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: false

# ä»£ç é«˜äº®
# åªèƒ½åœ¨ _config.yml ä¸­èµ·ä½œç”¨

#   # ä¸€é”®å¤åˆ¶
#   copy_btn: true

lazyload:
  enable: true

########################################################################

# æ‰“èµ
reward:
  enable: false
  icon: ri:hand-coin-line
  # ä¸éœ€è¦æ‰“èµï¼Œå°±æŠŠè¿™ä¸ªä½ç½®åšæˆäº†ç•™è¨€
  comment: å–œæ¬¢çš„è¯ï¼Œå°±ç•™ä¸‹ä¸€æ¡è¯„è®ºå§~
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: 
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: 
      color: "#12B7F5"
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: 
      color: "#2DC100"
      icon: ri:wechat-pay-line

########################################################################

# é¡µè„š
footer:
  since: 2020
  icon:
    name: ri:cloud-line
    animated: true
    color: "#0078E7"
  powered:
    # Hexo link (Powered by Hexo).
    enable: true

  # å¤‡æ¡ˆ
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # http://www.beian.miit.gov.cn
  beian:
    enable: false
    icp: å­¦å›­éƒ½å¸‚ICPå¤‡10032å·

  # è¿è¡Œæ—¶é—´
  live_time:
      enable: true
      prefix: æœ¬èŠ±å›­å·²é•¿è‰
      suffix: ï¼ˆÂ¯ï¹ƒÂ¯ï¼‰
      start_time: "2020-08-22T19:25:00"

  # è‡ªå®šä¹‰æ–‡æœ¬
  # Any custom text can be defined here.
  # custom_text: Hosted by <a href="https://pages.coding.me" rel="noopener" target="_blank">Coding Pages</a>
  custom_text: 'åšå®¢ç‰ˆæœ¬ï¼šVersion.2.1.4 | 
                <a href="https://icp.gov.moe" target="_blank" style="color:inherit"><img src="/images/moeicp.png" width="25" style="vertical-align:middle">èŒICPå¤‡ </a><a href="https://icp.gov.moe/?keyword=20232952" target="_blank" style="color:inherit"> 20232952 å·</a>
                '

  # æ”¯æŒè‡´è°¢
  support:
    enable: true
    title: Cloudflare
    link: https://www.cloudflare.com/
    logo: /images/CF_logo_stacked_blktype.svg
    prefix: ç”±å¥½äººä¸€ç”Ÿå¹³å®‰çš„
    suffix: æä¾›å…è´¹çš„ CDN åŠ é€Ÿ

########################################################################

# # Say
# say:
#   enable: true
#   api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
#   src: /js/say.js
#   # https://developer.hitokoto.cn/sentence/
#   hitokoto:
#     enable: true
#     api: https://v1.hitokoto.cn
say:
  enable: true
  api: /data/sentences.json
  hitokoto:
    enable: false

########################################################################

# é»˜å“€
mourn:
  enable: true
  days:
    - "6-4"

########################################################################

# è¯„è®º
comment:
  enable: true
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/misaka-clover/misaka-clover.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚
  candidates:
    - giscus
#    - utterances
#    - waline

# github_issues:
#   enable: false
#   username: misaka-clover
#   repository: misaka-clover.github.io
#   filters: is:issue

# github_discussions:
#   enable: false
#   username: misaka-clover
#   repository: misaka-clover.github.io

giscus:
  enable: true
  repo: misaka-clover/misaka-clover.github.io
  repo-id: MDEwOlJlcG9zaXRvcnkyODk0NzI1MzM=
  category: Announcements
  category-id: DIC_kwDOEUEAFc4CU_3i
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

# <script src="https://giscus.app/client.js"
#         data-repo="misaka-clover/misaka-clover.github.io"
#         data-repo-id="MDEwOlJlcG9zaXRvcnkyODk0NzI1MzM="
#         data-category="Announcements"
#         data-category-id="DIC_kwDOEUEAFc4CU_3i"
#         data-mapping="pathname"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="top"
#         data-theme="preferred_color_scheme"
#         data-lang="zh-CN"
#         crossorigin="anonymous"
#         async>
# </script>

# utterances:
#   enable: true
#   repo: misaka-clover/misaka-clover.github.io
#   issue-term: pathname
#   # label: comment
#   theme: github-light

# ä¸å†ä½¿ç”¨è¿™ä¸ªè¯„è®ºç³»ç»Ÿ
# waline:
#   enable: true
#   serverURL: https://mskclover-com.vercel.app
#   visitor: true
#   comment: true
#   avatar: 
#     url: https://sdn.geekzu.org/avatar/4674442b10d4160841c6a51bb09722e4?s=80
#     rounded: true
#   emoji:
#     - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
#     - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
#     - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/qq/
#   locale:
#     placeholder: è¯·ç•…æ‰€æ¬²è¨€å–”ï¼å·å·å‘Šè¯‰ä½ ï¼Œç™»å½• Gravatar åå¯è‡ªå®šä¹‰å¤´åƒæ¥ç€ï¼ˆ
#   requiredMeta: ["nick"]

########################################################################

# æœç´¢
# æœç´¢çš„èƒŒæ™¯
# search:
#   modal: true
#   bg_image: /images/background.jpg
#   dark_bg_image: /images/galaxy.jpg
#   placeholder: ä»Šå¤©æƒ³çœ‹çœ‹ä»€ä¹ˆå‘¢

engine_search:
  enable: true
  href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: mskclover.com

# # search
# # https://github.com/next-theme/hexo-generator-searchdb
# # æš‚æ—¶è¿˜æ˜¯ä¸ç”¨å†…ç½®çš„æœç´¢ï¼Œä¾æ‰˜ Bing å°±å¥½
# local_search:
#   enable: true

########################################################################

# è¿™æ˜¯è°·æ­Œåˆ†æï¼ˆGoogle Analyticsï¼‰
# æ³¨æ„ï¼šæœ€è¿‘æ–°å»ºçš„è°·æ­Œåˆ†æè´¦å·IDå·²ç»ä¿®æ”¹ï¼Œæ ¼å¼å¦‚ï¼šG-XXXXXXXXXXï¼Œå¯ä»¥ç›´æ¥å¡«å…¥idä¸€é¡¹ï¼ŒåŠŸèƒ½æ­£å¸¸ã€‚
# ç«™ç‚¹é…ç½®æ–‡ä»¶`_config.yml`ä¸­çš„ç«™ç‚¹éƒ¨ç½²çš„ url åº”ä¸ CNAME ä¸­çš„åŸŸåï¼ˆæˆ–xxxxx.github.ioï¼‰ä¸€è‡´

google_analytics:
  enable: true
  #id: UA-176081910-1
  id: G-6VWG03H880

# # å¼€å¯äº† Google SEO åéœ€è¦è·³è¿‡æ¸²æŸ“è¿™äº›æ–‡ä»¶
# # æ²¡æ‰¾åˆ°æ–‡ä»¶
# skip_render:
#   - README.md
#   - google_xxx.html

# è°·æ­Œå¹¿å‘Š
# æœªé…ç½®å®Œæˆ
google_adsense:
  enable: true
  client: pub-4618904761682457

########################################################################

# # ä¸è’œå­æ˜¯ä¸€æ¬¾è½»é‡æç®€çš„ç½‘ç«™è®¡æ•°å™¨ã€‚
# # ä½¿ç”¨è¯´æ˜ï¼šhttps://ibruce.info/2015/04/04/busuanzi
# busuanzi:
#   enable: false
#   site_uv: true
#   site_uv_icon: ri:user-line
#   site_pv: true
#   site_pv_icon: ri:eye-line
#   page_pv: true
#   page_pv_icon: ri:eye-line
# # ä¸çŸ¥é“ä¸ºä»€ä¹ˆï¼Œè¿™ä¸ªè®¡æ•°å™¨æœ‰é—®é¢˜ï¼Œæ˜¾ç¤ºå‡ ç™¾ä¸‡æ¬¡çš„è®¿é—®é‡â€¦â€¦


# LeanCloudåœ¨å›½å†…ä¸å†å¯ç”¨
# # åŸºäº LeanCloud çš„è®¿é—®è€…ç»Ÿè®¡ï¼Œæ˜¾ç¤ºæ¯ç¯‡æ–‡ç« çš„è®¿é—®é‡ã€‚
# leancloud_visitors:
#   enable: true
#   app_id: ORivKcH7ctPK1d4c7xLn1wgi-MdYXbMMI
#   app_key: 6cWYWOhAeaacKbuNuGO0GgSs
#   # Required for apps from CN region
#   server_url: https://mskclover-com.vercel.app

# è¯æ•°ç»Ÿè®¡å’Œé˜…è¯»æ—¶é—´çš„ä¼°è®¡
wordcount:
  enable: true
  count: true
  time: true

# KaTeX
katex:
  copy_tex: true
  global: false

# mermaid
mermaid:
  enable: false
  options: # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    startOnload: true # default true
  global: false # default true














